"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-sdk' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Module NOT installed (peer standalone absent in the CI env) →
  test is SKIPPED via `pytest.importorskip`. The umbrella's CI
  (which installs every peer) catches cross-package renames.
"""

from __future__ import annotations

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex_app",
    "scitex_ui",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import(module_name):
    """Importing scitex-sdk's declared cross-package dependency must succeed.

    The skip is taken on the ROOT package and the FULL path is then hard
    imported. Skipping on the full path — ``importorskip(module_name)`` —
    made this gate incapable of failing: a RENAMED or DELETED submodule
    raises ``ModuleNotFoundError``, which ``importorskip`` converts into a
    skip, so the run reports green for precisely the breakage the gate
    exists to catch. Splitting the two makes the peer's absence a skip and
    the submodule's absence a failure.

    The skip cannot simply be dropped: these peers are optional extras, so
    a blanket hard import would fail a legitimately lean install.
    """
    # Arrange — skip on the ROOT so a lean install skips instead of failing.
    root_name = module_name.split(".")[0]
    pytest.importorskip(root_name)
    # Act
    module = importlib.import_module(module_name)
    # Assert
    assert module.__name__ == module_name
